Detect monitors and screen width, set View dialog width accordingle

diff --git a/blobthemes b/blobthemes
--- a/blobthemes
+++ b/blobthemes
@@ -41,6 +41,7 @@
 #
 # TODO:
 # Deal with per-desktop conky situations;
+# Adjust dialog width for dual screens
 # 
 #### VARIABLES #########################################################
 CONFIGPATH="$HOME/.config/blob"
@@ -85,12 +86,13 @@ DIALOG="yad --center --undecorated --borders=20 --window-icon=gtk-preferences"
 DIALOGDEC="yad --center  --borders=20 --window-icon=gtk-preferences"
 TITLE="BLOB Config Manager"
 IMG="--image="
-IMGPATH="Bunsenlabs-flame-256.svg"
+IMGPATH="$HOME/tmp/Bunsenlabs-flame-256.svg"
 T="--text="
 OK="--button=OK:0"
 CANCEL="--button=gtk-cancel:1"
 EXIT="--button=gtk-quit:1"
 CLOSE="--button=gtk-close:1"
+DLGWIDTH="--width="
 TXTINTRO="\n\n<big><b>BunsenLabs\n\nOpenbox Configuration Manager</b></big>\n\n\n \
 <b>Save or Restore settings for:</b>\n\n \
 \t\tOpenbox theme\n \
@@ -164,6 +166,35 @@ function getSet(){      # get name of currently set BLOB config
         fi
     elif [[ $NUMDIRS -gt 0 ]] && [[ -f $CURSESSION ]];then
         SET=$(cat $CURSESSION)
+    fi
+}
+
+function countMonitors(){ #test for more than 2 monitors connected.
+    MON=$(xrandr -q | grep -c " connected")
+    case $MON in
+        1 )     W=600
+                ;;
+        2 )     getScreenPos
+                ;;
+        3 )     W=1200
+                ;;
+        * )     W=600
+                echo -e "Script cannot deal with these monitors.\
+                Setting dialog width = 500" >&2
+    esac
+}
+function getScreenPos(){
+    # Get monitors geometry and position ( w x h x offset_x offset_y )
+    mons=$(echo $(xrandr -q | awk '/ connected/ {if ($3=="primary") print $1,$4; else print $1,$3}'))
+    read monA monAgeom monB monBgeom <<< "$mons"
+
+    monApos=$(echo $monAgeom | awk -F "+" '{print $2}') # get offset_x
+    monBpos=$(echo $monBgeom | awk -F "+" '{print $2}')
+    
+    if [[ $monApos = $monBpos ]];then
+        W=500
+    else
+        W=800
     fi
 }
 
@@ -518,7 +549,7 @@ function getScrot(){            # Get screenshot & create thumbnail
 
     ShowRootMenu    # display root menu for the scrot
 
-    scrot -t 15 "$SCROT.jpg"
+    scrot -t 12 "$SCROT.jpg"    # scrot thumbnail @12% fulsize
 
     THUMB=$(find $CONFIGPATH -maxdepth 1 -type f -name "*-thumb.jpg" 2>/dev/null)
     mv $THUMB $CONFIGDIR
@@ -797,7 +828,7 @@ function restoreSettings(){
             --button="Add New:3" \
             --button="Delete:2" --button="Restore:0" --button="gtk-quit:1" \
             --always-print-result \
-            --width=500 --height=500 --center --image-preview \
+            --width=$W --height=500 --center --image-preview \
             --expand-column=2 \
             --expand-column=3 \
             --column="Last Set:IMG" \
@@ -929,6 +960,7 @@ mkdir -p "$CONFIGPATH"
 if [[ ! -f $CURSESSION ]];then
     touch "$CURSESSION"
 fi
+countMonitors
 getSet
 if (( $NUMDIRS == 0 ));then
     Intro
